### ISSUE TITLE
Boxen scripts broken for new starters

### ISSUE THREAD

**Issue by benhyland** [alphagov/gds-boxen#208]
As a new starter, I was advised by several people and by the instructions on govuk-puppet/development to provision my laptop with this project. Unfortunately, it no longer works (for example, it tries to dowload a github repo that no longer exists).

This is quite confusing and time consuming for newbies, so we should either fix this **and introduce automated testing**, or delete it and update any documentation that might exist elsewhere.

**Comment by alexmuller** [comment]
Do you have examples of things that don't work? [My manifest file](https://github.com/alphagov/gds-boxen/blob/4f94c6e15381aa409c17a8afb4df85189ad7af7b/modules/people/manifests/alexmuller.pp) runs fine and sets things up exactly as I think it should.

**Comment by benhyland** [comment]
Never having used boxen before I was just following the govuk-puppet and
gds-boxen instructions, which didn't mention the need to add a per-user
manifest file (but perhaps I misunderstood them).
I don't have a record of the error I encountered, sorry - I recall I gave
up and set up my machine manually when the script tried to clone a repo
which doesn't exist any more. I probably have lower tolerance for
automation failures than the average new starter since I am unfamiliar with
the majority of the tech stack at the moment.
If you believe the script works as intended for a new starter you could
close the ticket.

**Comment by tijmenb** [comment]
@carvil got this error while running:

```
Cannot write a changed lockfile while frozen.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1564:in `path': no implicit conversion of nil into String (TypeError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1564:in `fu_each_src_dest0'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/util.rb:21:in `cp_r'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/source/githubtarball/repo.rb:56:in `install_version!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/source/githubtarball.rb:84:in `install!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `block in install_manifests'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/cli.rb:94:in `install!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/lib/librarian/puppet/cli.rb:69:in `install'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-1.0.9/bin/librarian-puppet:7:in `<top (required)>'
    from /opt/boxen/repo/bin/librarian-puppet:16:in `load'
    from /opt/boxen/repo/bin/librarian-puppet:16:in `<main>'
Can't run Puppet, fetching dependencies with librarian failed.```
```

**Comment by annashipman** [comment]
What OS were you using, @benhyland? I had some issues on Yosemite.

**Comment by benhyland** [comment]
@annashipman I was also using Yosemite, but I don't believe my issues were related to the OS.
